apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-test
  namespace: default
  labels:
    app: async-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: async-test
  template:
    metadata:
      labels:
        app: async-test
    spec:
      containers:
      - name:  async-test
        image:  local-test:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
          periodSeconds: 5
        ports:
        - containerPort:  80
          name:  async-test
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: async-test
spec:
  type: NodePort
  selector:
    app: async-test
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31900
